import { useState, type FormEvent } from "react";

type Props = { onSubmit: (body: Record<string, unknown>) => void; pending: boolean };

export function TrainingForm({ onSubmit, pending }: Props) {
  const [form, setForm] = useState({ dataset_version: "fixture:v1", split_version: "split:v1", language: "singlish", base_model: "mlx-community/Qwen2.5-3B-Instruct-4bit", model_version: "qwen2.5-3b-4bit", model_license: "review-required", seed: "13", objective: "supervised fine-tuning", unified_memory_mb: "0" });
  const update = (key: keyof typeof form, value: string) => setForm({ ...form, [key]: value });
  const submit = (event: FormEvent) => { event.preventDefault(); onSubmit({ training_engine: "mlx_lm", dataset_version: form.dataset_version, split_version: form.split_version, language_slices: [form.language], base_model: form.base_model, model_version: form.model_version, model_license: form.model_license, seed: Number(form.seed), objective: form.objective, unified_memory_mb: Number(form.unified_memory_mb), adapter_config: { mode: "lora" } }); };
  return <form className="panel form-grid" onSubmit={submit}><div className="field"><label>Dataset version</label><input value={form.dataset_version} onChange={(e) => update("dataset_version", e.target.value)} /></div><div className="field"><label>Split version</label><input value={form.split_version} onChange={(e) => update("split_version", e.target.value)} /></div><div className="field"><label>Language slice</label><select value={form.language} onChange={(e) => update("language", e.target.value)}><option value="singlish">Singapore English/Singlish</option><option value="malay">Malay</option><option value="tamil">Tamil</option><option value="singapore_mandarin">Singapore Mandarin</option></select></div><div className="field"><label>Base model</label><input value={form.base_model} onChange={(e) => update("base_model", e.target.value)} /></div><div className="field"><label>Model version</label><input value={form.model_version} onChange={(e) => update("model_version", e.target.value)} /></div><div className="field"><label>Model license</label><input value={form.model_license} onChange={(e) => update("model_license", e.target.value)} /></div><div className="field"><label>Seed</label><input type="number" value={form.seed} onChange={(e) => update("seed", e.target.value)} /></div><div className="field"><label>Unified memory (MB)</label><input type="number" value={form.unified_memory_mb} onChange={(e) => update("unified_memory_mb", e.target.value)} /></div><div className="field field--wide"><label>Objective</label><input value={form.objective} onChange={(e) => update("objective", e.target.value)} /></div><div className="field field--wide"><p className="muted">Training engine: MLX-LM. A completed job is not publication evidence until downstream evaluation is registered.</p><button className="action" disabled={pending}>{pending ? "Submitting…" : "Queue MLX-LM job"}</button></div></form>;
}